version: '3.8'

services:
  laravel:
    build:
      context: ./laravel
    container_name: laravel
    environment:
      - APP_PORT=${LARAVEL_PORT}
      - DB_CONNECTION=mysql
      - DB_HOST=mariadb
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=password
    volumes:
      - ./laravel:/var/www/html
    networks:
      - app-network
    depends_on:
      - mariadb
    ports:
      - "${LARAVEL_PORT}:80"

  react:
    build:
      context: ./react-app
    container_name: react-app
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./react-app:/usr/src/app
    ports:
      - "${REACT_PORT}:3000"
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=laravel
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mariadb-data:
