version: '3.8'
services:
  # Laravel service using Sail
  laravel:
    build:
      context: ./laravel
      dockerfile: Dockerfile
    container_name: laravel-app
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=mydatabase
      - DB_USERNAME=root
      - DB_PASSWORD=password
    networks:
      - app-network

  # React service
  react:
    build:
      context: ./react-app
    container_name: react-app
    stdin_open: true
    volumes:
      - ./react-app:/app
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

  # MariaDB service
  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - app-network

  # Nginx service
  nginx:
    image: nginx:alpine
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${LARAVEL_PORT}:80" # Expose the Laravel app on port 8003
    depends_on:
      - laravel
      - react
    networks:
      - app-network

# Docker network for all services
networks:
  app-network:
    driver: bridge

# Volumes for MariaDB
volumes:
  dbdata:
    driver: local
